server:
  port: 8083
spring:
  application:
    name: audit
  kafka:
    bootstrap-servers:
      - localhost:29092
    consumer:
      group-id: "audit"
logging:
  pattern:
    level: "%5p [${spring.application.name:}]"
