server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers:
      - localhost:29092
  application:
    name: microservice-2
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
