server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/microservice_2_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin1234}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  application:
    name: microservice-2
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
